package ru.novaris.novoscan.domain;

/**
 * AccountRoles generated by hbm2java
 */
public class AccountRoles implements java.io.Serializable {

	/**
	 * 
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long acrlId;
	private long acrlAcctId;
	private long acrlRoleId;
	private String acrlRoleName;
	private String acrlLoginName;

	public AccountRoles() {
	}

	public AccountRoles(long acrlId, long acrlAcctId, long acrlRoleId) {
		this.acrlId = acrlId;
		this.acrlAcctId = acrlAcctId;
		this.acrlRoleId = acrlRoleId;
	}

	public long getAcrlId() {
		return this.acrlId;
	}

	public void setAcrlId(long acrlId) {
		this.acrlId = acrlId;
	}

	public long getAcrlRoleId() {
		return this.acrlRoleId;
	}

	public void setAcrlRoleId(long acrlRoleId) {
		this.acrlRoleId = acrlRoleId;
	}
	public long getAcrlAcctId() {
		return this.acrlAcctId;
	}

	public void setAcrlAcctId(long acrlAcctId) {
		this.acrlAcctId = acrlAcctId;
	}
	public String getAcrlRoleName() {
		return this.acrlRoleName;
	}

	public void setAcrlRoleName(String acrlRoleName) {
		this.acrlRoleName = acrlRoleName;
	}	

	
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountRoles))
			return false;
		AccountRoles castOther = (AccountRoles) other;

		return (this.getAcrlId() == castOther.getAcrlId())
				&& (this.getAcrlAcctId() == castOther.getAcrlAcctId())
				&& (this.getAcrlRoleId() == castOther.getAcrlRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAcrlId();
		result = 37 * result + (int) this.getAcrlAcctId();
		result = 37 * result + (int) this.getAcrlRoleId();
		return result;
	}

	public String getAcrlLoginName() {
		return acrlLoginName;
	}

	public void setAcrlLoginName(String acrlLoginName) {
		this.acrlLoginName = acrlLoginName;
	}
}
