package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * DataSensor generated by hbm2java
 */
public class DataSensor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1889007427825921620L;


	private long dasnId;

	//private SprvSensors sprvSensors;
	
	private long dasnSpsnId;

	private long dasnUid;

	private Date dasnDatetime;

	private double dasnLatitude;

	private double dasnLongitude;

	private long dasnStatus;

	private Long dasnSatUsed;

	private Long dasnZoneAlarm;

	private Long dasnMacroId;

	private Long dasnMacroSrc;

	private Double dasnSog;

	private Double dasnCourse;

	private Double dasnHdop;

	private Double dasnHgeo;

	private Double dasnHmet;

	private Long dasnGpio;

	private Long dasnAdc;

	private Double dasnTemp;

	private long dasnType;

	private String dasnXml;

	private Date dasnDtm;

	private String dasnVehicle;

	public DataSensor() {
	}

	public DataSensor(long dasnId, long dasnSpsnId, long dasnUid,
			Date dasnDatetime, double dasnLatitude, double dasnLongitude,
			long dasnStatus, long dasnType, String dasnXml, Date dasnDtm) {
		this.dasnId = dasnId;
		//this.sprvSensors = sprvSensors;
		this.dasnSpsnId = dasnSpsnId;
		this.dasnUid = dasnUid;
		this.dasnDatetime = dasnDatetime;
		this.dasnLatitude = dasnLatitude;
		this.dasnLongitude = dasnLongitude;
		this.dasnStatus = dasnStatus;
		this.dasnType = dasnType;
		this.dasnXml = dasnXml;
		this.dasnDtm = dasnDtm;
	}

	public DataSensor(long dasnId, long dasnSpsnId, long dasnUid,
			Date dasnDatetime, double dasnLatitude, double dasnLongitude,
			long dasnStatus, Long dasnSatUsed, Long dasnZoneAlarm,
			Long dasnMacroId, Long dasnMacroSrc, Double dasnSog,
			Double dasnCourse, Double dasnHdop, Double dasnHgeo,
			Double dasnHmet, Long dasnGpio, Long dasnAdc, Double dasnTemp,
			long dasnType, String dasnXml, Date dasnDtm, String dasnVehicle) {
		this.dasnId = dasnId;
		//this.sprvSensors = sprvSensors;
		this.dasnSpsnId = dasnSpsnId;
		this.dasnUid = dasnUid;
		this.dasnDatetime = dasnDatetime;
		this.dasnLatitude = dasnLatitude;
		this.dasnLongitude = dasnLongitude;
		this.dasnStatus = dasnStatus;
		this.dasnSatUsed = dasnSatUsed;
		this.dasnZoneAlarm = dasnZoneAlarm;
		this.dasnMacroId = dasnMacroId;
		this.dasnMacroSrc = dasnMacroSrc;
		this.dasnSog = dasnSog;
		this.dasnCourse = dasnCourse;
		this.dasnHdop = dasnHdop;
		this.dasnHgeo = dasnHgeo;
		this.dasnHmet = dasnHmet;
		this.dasnGpio = dasnGpio;
		this.dasnAdc = dasnAdc;
		this.dasnTemp = dasnTemp;
		this.dasnType = dasnType;
		this.dasnXml = dasnXml;
		this.dasnDtm = dasnDtm;
		this.dasnVehicle = dasnVehicle;
	}

	public long getDasnId() {
		return this.dasnId;
	}

	public void setDasnId(long dasnId) {
		this.dasnId = dasnId;
	}

/*	
    public SprvSensors getSprvSensors() {
		return this.sprvSensors;
	} 
	public void setSprvSensors(SprvSensors sprvSensors) {
		this.sprvSensors = sprvSensors;
	}
*/

	public long getDasnUid() {
		return this.dasnUid;
	}

	public void setDasnUid(long dasnUid) {
		this.dasnUid = dasnUid;
	}

	public Date getDasnDatetime() {
		return this.dasnDatetime;
	}

	public void setDasnDatetime(Date dasnDatetime) {
		this.dasnDatetime = dasnDatetime;
	}

	public double getDasnLatitude() {
		return this.dasnLatitude;
	}

	public void setDasnLatitude(double dasnLatitude) {
		this.dasnLatitude = dasnLatitude;
	}

	public double getDasnLongitude() {
		return this.dasnLongitude;
	}

	public void setDasnLongitude(double dasnLongitude) {
		this.dasnLongitude = dasnLongitude;
	}

	public long getDasnStatus() {
		return this.dasnStatus;
	}

	public void setDasnStatus(long dasnStatus) {
		this.dasnStatus = dasnStatus;
	}

	public Long getDasnSatUsed() {
		return this.dasnSatUsed;
	}

	public void setDasnSatUsed(Long dasnSatUsed) {
		this.dasnSatUsed = dasnSatUsed;
	}

	public Long getDasnZoneAlarm() {
		return this.dasnZoneAlarm;
	}

	public void setDasnZoneAlarm(Long dasnZoneAlarm) {
		this.dasnZoneAlarm = dasnZoneAlarm;
	}

	public Long getDasnMacroId() {
		return this.dasnMacroId;
	}

	public void setDasnMacroId(Long dasnMacroId) {
		this.dasnMacroId = dasnMacroId;
	}

	public Long getDasnMacroSrc() {
		return this.dasnMacroSrc;
	}

	public void setDasnMacroSrc(Long dasnMacroSrc) {
		this.dasnMacroSrc = dasnMacroSrc;
	}

	public Double getDasnSog() {
		return this.dasnSog;
	}

	public void setDasnSog(Double dasnSog) {
		this.dasnSog = dasnSog;
	}

	public Double getDasnCourse() {
		return this.dasnCourse;
	}

	public void setDasnCourse(Double dasnCourse) {
		this.dasnCourse = dasnCourse;
	}

	public Double getDasnHdop() {
		return this.dasnHdop;
	}

	public void setDasnHdop(Double dasnHdop) {
		this.dasnHdop = dasnHdop;
	}

	public Double getDasnHgeo() {
		return this.dasnHgeo;
	}

	public void setDasnHgeo(Double dasnHgeo) {
		this.dasnHgeo = dasnHgeo;
	}

	public Double getDasnHmet() {
		return this.dasnHmet;
	}

	public void setDasnHmet(Double dasnHmet) {
		this.dasnHmet = dasnHmet;
	}

	public Long getDasnGpio() {
		return this.dasnGpio;
	}

	public void setDasnGpio(Long dasnGpio) {
		this.dasnGpio = dasnGpio;
	}

	public Long getDasnAdc() {
		return this.dasnAdc;
	}

	public void setDasnAdc(Long dasnAdc) {
		this.dasnAdc = dasnAdc;
	}

	public Double getDasnTemp() {
		return this.dasnTemp;
	}

	public void setDasnTemp(Double dasnTemp) {
		this.dasnTemp = dasnTemp;
	}

	public long getDasnType() {
		return this.dasnType;
	}

	public void setDasnType(long dasnType) {
		this.dasnType = dasnType;
	}

	public String getDasnXml() {
		return this.dasnXml;
	}

	public void setDasnXml(String dasnXml) {
		this.dasnXml = dasnXml;
	}

	public Date getDasnDtm() {
		return this.dasnDtm;
	}

	public void setDasnDtm(Date dasnDtm) {
		this.dasnDtm = dasnDtm;
	}

	public String getDasnVehicle() {
		return this.dasnVehicle;
	}

	public void setDasnVehicle(String dasnVehicle) {
		this.dasnVehicle = dasnVehicle;
	}

	public void setDasnSpsnId(long dasnSpsnId) {
		this.dasnSpsnId = dasnSpsnId;
	}

	public long getDasnSpsnId() {
		return dasnSpsnId;
	}

}
