package ru.novaris.novoscan.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * GisData generated by hbm2java
 */
public class GisData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int gsdtId;

	private GisObjects gisObjects;

	private GisPointTypes gisPointTypes;

	private Date gsdtDt;

	private BigDecimal gsdtPiket;

	private String gsdtInfo;

	private Serializable gsdtLineGeom;

	private Serializable gsdtPointGeom;

	public GisData() {
	}

	public GisData(int gsdtId, GisObjects gisObjects,
			GisPointTypes gisPointTypes, Date gsdtDt, BigDecimal gsdtPiket) {
		this.gsdtId = gsdtId;
		this.gisObjects = gisObjects;
		this.gisPointTypes = gisPointTypes;
		this.gsdtDt = gsdtDt;
		this.gsdtPiket = gsdtPiket;
	}

	public GisData(int gsdtId, GisObjects gisObjects,
			GisPointTypes gisPointTypes, Date gsdtDt, BigDecimal gsdtPiket,
			String gsdtInfo, Serializable gsdtLineGeom,
			Serializable gsdtPointGeom) {
		this.gsdtId = gsdtId;
		this.gisObjects = gisObjects;
		this.gisPointTypes = gisPointTypes;
		this.gsdtDt = gsdtDt;
		this.gsdtPiket = gsdtPiket;
		this.gsdtInfo = gsdtInfo;
		this.gsdtLineGeom = gsdtLineGeom;
		this.gsdtPointGeom = gsdtPointGeom;
	}

	public int getGsdtId() {
		return this.gsdtId;
	}

	public void setGsdtId(int gsdtId) {
		this.gsdtId = gsdtId;
	}

	public GisObjects getGisObjects() {
		return this.gisObjects;
	}

	public void setGisObjects(GisObjects gisObjects) {
		this.gisObjects = gisObjects;
	}

	public GisPointTypes getGisPointTypes() {
		return this.gisPointTypes;
	}

	public void setGisPointTypes(GisPointTypes gisPointTypes) {
		this.gisPointTypes = gisPointTypes;
	}

	public Date getGsdtDt() {
		return this.gsdtDt;
	}

	public void setGsdtDt(Date gsdtDt) {
		this.gsdtDt = gsdtDt;
	}

	public BigDecimal getGsdtPiket() {
		return this.gsdtPiket;
	}

	public void setGsdtPiket(BigDecimal gsdtPiket) {
		this.gsdtPiket = gsdtPiket;
	}

	public String getGsdtInfo() {
		return this.gsdtInfo;
	}

	public void setGsdtInfo(String gsdtInfo) {
		this.gsdtInfo = gsdtInfo;
	}

	public Serializable getGsdtLineGeom() {
		return this.gsdtLineGeom;
	}

	public void setGsdtLineGeom(Serializable gsdtLineGeom) {
		this.gsdtLineGeom = gsdtLineGeom;
	}

	public Serializable getGsdtPointGeom() {
		return this.gsdtPointGeom;
	}

	public void setGsdtPointGeom(Serializable gsdtPointGeom) {
		this.gsdtPointGeom = gsdtPointGeom;
	}

}
