package ru.novaris.novoscan.domain;

import java.math.BigDecimal;
import java.util.Date;


/**
 * GisObjects generated by hbm2java
 */
public class GisDataPoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int gsdtId;

	private long gsdtGsobId;

	private long gsdtGsptId;

	private Date gsdtDt;

	private BigDecimal gsdtPiket;

	private String gsdtInfo;

	private String gsdtPoint;

	public GisDataPoint() {
	}

	public GisDataPoint(int gsdtId, long gsdtGsobId, long gsdtGsptId,
			Date gsdtDt, BigDecimal gsdtPiket) {
		this.gsdtId = gsdtId;
		this.gsdtGsobId = gsdtGsobId;
		this.gsdtGsptId = gsdtGsptId;
		this.gsdtDt = gsdtDt;
		this.gsdtPiket = gsdtPiket;
	}

	public int getGsdtId() {
		return gsdtId;
	}

	public void setGsdtId(int gsdtId) {
		this.gsdtId = gsdtId;
	}

	public long getGsdtGsobId() {
		return gsdtGsobId;
	}

	public void setGsdtGsobId(long gsdtGsobId) {
		this.gsdtGsobId = gsdtGsobId;
	}

	public long getGsdtGsptId() {
		return gsdtGsptId;
	}

	public void setGsdtGsptId(long gsdtGsptId) {
		this.gsdtGsptId = gsdtGsptId;
	}

	public Date getGsdtDt() {
		return gsdtDt;
	}

	public void setGsdtDt(Date gsdtDt) {
		this.gsdtDt = gsdtDt;
	}

	public BigDecimal getGsdtPiket() {
		return gsdtPiket;
	}

	public void setGsdtPiket(BigDecimal gsdtPiket) {
		this.gsdtPiket = gsdtPiket;
	}

	public String getGsdtInfo() {
		return gsdtInfo;
	}

	public void setGsdtInfo(String gsdtInfo) {
		this.gsdtInfo = gsdtInfo;
	}

	public String getGsdtPoint() {
		return gsdtPoint;
	}
	
	public void setGsdtPoint(String gsdtPoint) {
		this.gsdtPoint = gsdtPoint;
	}
}
