package ru.novaris.novoscan.domain;
import java.util.Date;


/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long roleId;
	private String roleName;
	private String roleDesc;
	private Date roleDate;

	public Roles() {
	}

	public Roles(long roleId, String roleName, Date roleDate) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDate = roleDate;
	}

	public Roles(long roleId, String roleName, String roleDesc, Date roleDate) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleDate = roleDate;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Date getRoleDate() {
		return this.roleDate;
	}

	public void setRoleDate(Date roleDate) {
		this.roleDate = roleDate;
	}


}
