package ru.novaris.novoscan.domain;

import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;

/**
 * SprvObjects generated by hbm2java
 */
public class SprvObjects implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spobId;

	//private SprvObjectTypes sprvObjectTypes;

	//private SprvClients sprvClients;


	private long spobSpclId;

	private long spobSpotId;

	private String spobName;

	private String spobDesc;

	private Date spobDtCreate;

	private Date spobDtModify;

	private Date spobDtClose;

	private String spobSpotName;

	private String spobSpclName;

//	private Set sprvModuleses = new HashSet(0);

	public SprvObjects() {
	}

	public SprvObjects(long spobId
//			,SprvObjectTypes sprvObjectTypes
//			,SprvClients sprvClients
			,long spobSpotId
			,long spobSpclId
			,String spobName, String spobDesc,
			Date spobDtCreate, Date spobDtModify) {
		this.spobId = spobId;
//		this.sprvObjectTypes = sprvObjectTypes;
//		this.sprvClients = sprvClients;
		this.spobSpclId = spobSpclId;
		this.spobSpotId = spobSpotId;
		this.spobName = spobName;
		this.spobDesc = spobDesc;
		this.spobDtCreate = spobDtCreate;
		this.spobDtModify = spobDtModify;
	}

/*	public SprvObjects(long spobId, SprvObjectTypes sprvObjectTypes,
			SprvClients sprvClients, String spobName, String spobDesc,
			Date spobDtCreate, Date spobDtModify, Date spobDtClose,
			Set sprvModuleses) {
		this.spobId = spobId;
		this.sprvObjectTypes = sprvObjectTypes;
		this.sprvClients = sprvClients;
		this.spobName = spobName;
		this.spobDesc = spobDesc;
		this.spobDtCreate = spobDtCreate;
		this.spobDtModify = spobDtModify;
		this.spobDtClose = spobDtClose;
		this.sprvModuleses = sprvModuleses;
	}*/

	public long getSpobId() {
		return this.spobId;
	}

	public void setSpobId(long spobId) {
		this.spobId = spobId;
	}

/*	public SprvObjectTypes getSprvObjectTypes() {
		return this.sprvObjectTypes;
	}

	public void setSprvObjectTypes(SprvObjectTypes sprvObjectTypes) {
		this.sprvObjectTypes = sprvObjectTypes;
	}

	public SprvClients getSprvClients() {
		return this.sprvClients;
	}

	public void setSprvClients(SprvClients sprvClients) {
		this.sprvClients = sprvClients;
	}
*/
	public String getSpobName() {
		return this.spobName;
	}

	public void setSpobName(String spobName) {
		this.spobName = spobName;
	}

	public String getSpobDesc() {
		return this.spobDesc;
	}

	public void setSpobDesc(String spobDesc) {
		this.spobDesc = spobDesc;
	}

	public Date getSpobDtCreate() {
		return this.spobDtCreate;
	}

	public void setSpobDtCreate(Date spobDtCreate) {
		this.spobDtCreate = spobDtCreate;
	}

	public Date getSpobDtModify() {
		return this.spobDtModify;
	}

	public void setSpobDtModify(Date spobDtModify) {
		this.spobDtModify = spobDtModify;
	}

	public Date getSpobDtClose() {
		return this.spobDtClose;
	}

	public void setSpobDtClose(Date spobDtClose) {
		this.spobDtClose = spobDtClose;
	}

/*	public Set getSprvModuleses() {
		return this.sprvModuleses;
	}

	public void setSprvModuleses(Set sprvModuleses) {
		this.sprvModuleses = sprvModuleses;
	}*/
	public long getSpobSpotId() {
		return this.spobSpotId;
	}

	public void setSpobSpotId(long spobSpotId) {
		this.spobSpotId = spobSpotId;
	}
	public long getSpobSpclId() {
		return this.spobSpclId;
	}

	public void setSpobSpclId(long spobSpclId) {
		this.spobSpclId = spobSpclId;
	}

	public String getSpobSpclName() {
		// TODO Auto-generated method stub
		return spobSpclName;
	}

	public void setSpobSpclName(String spobSpclName) {
		// TODO Auto-generated method stub
		this.spobSpclName = spobSpclName;
	}
	
	public String getSpobSpotName() {
		// TODO Auto-generated method stub
		return this.spobSpotName;
	}
	public void setSpobSpotName(String spobSpotName) {
		// TODO Auto-generated method stub
		this.spobSpotName = spobSpotName;
	}

}
