package ru.novaris.novoscan.domain;

/*import java.util.HashSet;
import java.util.Set;
*/
/**
 * SprvUnits generated by hbm2java
 */
public class SprvUnits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int spunId;

	private int spunSpusId;

	private String spunName;

	private String spunAbbrEn;

	private String spunAbbrRu;

//	private Set sprvCalibrates = new HashSet(0);

	public SprvUnits() {
	}

	public SprvUnits(int spunId, int spunSpusId, String spunName,
			String spunAbbrEn, String spunAbbrRu) {
		this.spunId = spunId;
		this.spunSpusId = spunSpusId;
		this.spunName = spunName;
		this.spunAbbrEn = spunAbbrEn;
		this.spunAbbrRu = spunAbbrRu;
	}

/*	public SprvUnits(int spunId, int spunSpusId, String spunName,
			String spunAbbrEn, String spunAbbrRu, Set sprvCalibrates) {
		this.spunId = spunId;
		this.spunSpusId = spunSpusId;
		this.spunName = spunName;
		this.spunAbbrEn = spunAbbrEn;
		this.spunAbbrRu = spunAbbrRu;
		this.sprvCalibrates = sprvCalibrates;
	}*/

	public int getSpunId() {
		return this.spunId;
	}

	public void setSpunId(int spunId) {
		this.spunId = spunId;
	}

	public int getSpunSpusId() {
		return this.spunSpusId;
	}

	public void setSpunSpusId(int spunSpusId) {
		this.spunSpusId = spunSpusId;
	}

	public String getSpunName() {
		return this.spunName;
	}

	public void setSpunName(String spunName) {
		this.spunName = spunName;
	}

	public String getSpunAbbrEn() {
		return this.spunAbbrEn;
	}

	public void setSpunAbbrEn(String spunAbbrEn) {
		this.spunAbbrEn = spunAbbrEn;
	}

	public String getSpunAbbrRu() {
		return this.spunAbbrRu;
	}

	public void setSpunAbbrRu(String spunAbbrRu) {
		this.spunAbbrRu = spunAbbrRu;
	}

/*	public Set getSprvCalibrates() {
		return this.sprvCalibrates;
	}

	public void setSprvCalibrates(Set sprvCalibrates) {
		this.sprvCalibrates = sprvCalibrates;
	}*/

}
