package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * SprvModules generated by hbm2java
 */
public class SprvModules implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spmdId;

	/*
	private SprvModuleTypes sprvModuleTypes;

	private SprvObjects sprvObjects;
	*/
	private long spmdSpmtId;

	private long spmdSpobId;
	
	private double spmdUid;

	private String spmdName;

	private Date spmdDtCreate;

	private Date spmdDtClose;

	private String spmdUser;

	private String spmdImei;

	private String spmdNumb;

	private String spmdDesc;

	private String spmdSpmtName;

	private String spmdSpobName;

	public SprvModules() {
	}

	public SprvModules(long spmdId, 
			//SprvModuleTypes sprvModuleTypes,
			//SprvObjects sprvObjects,
			long spmdSpmtId,
			long spmdSpobId,
			double spmdUid, String spmdName,
			Date spmdDtCreate, String spmdImei, String spmdNumb, String spmdDesc) {
		this.spmdId = spmdId;
		//this.sprvModuleTypes = sprvModuleTypes;
		//this.sprvObjects = sprvObjects;
		this.spmdSpmtId = spmdSpmtId;
		this.spmdSpobId = spmdSpobId;
		this.spmdUid = spmdUid;
		this.spmdName = spmdName;
		this.spmdDtCreate = spmdDtCreate;
		this.spmdImei = spmdImei;
		this.spmdNumb = spmdNumb;
		this.spmdDesc = spmdDesc;
	}

	public SprvModules(long spmdId, 			//SprvModuleTypes sprvModuleTypes,
			//SprvObjects sprvObjects,
			long spmdSpmtId,
			long spmdSpobId, double spmdUid, String spmdName,
			Date spmdDtCreate, Date spmdDtClose, String spmdUser,
			String spmdImei, String spmdNumb, String spmdDesc) {
		this.spmdId = spmdId;
		//this.sprvModuleTypes = sprvModuleTypes;
		//this.sprvObjects = sprvObjects;
		this.spmdSpmtId = spmdSpmtId;
		this.spmdSpobId = spmdSpobId;
		this.spmdUid = spmdUid;
		this.spmdName = spmdName;
		this.spmdDtCreate = spmdDtCreate;
		this.spmdDtClose = spmdDtClose;
		this.spmdUser = spmdUser;
		this.spmdImei = spmdImei;
		this.spmdNumb = spmdNumb;
		this.spmdDesc = spmdDesc;
	}

	public long getSpmdId() {
		return this.spmdId;
	}

	public void setSpmdId(long spmdId) {
		this.spmdId = spmdId;
	}

/*	public SprvModuleTypes getSprvModuleTypes() {
		return this.sprvModuleTypes;
	}

	public void setSprvModuleTypes(SprvModuleTypes sprvModuleTypes) {
		this.sprvModuleTypes = sprvModuleTypes;
	}

	public SprvObjects getSprvObjects() {
		return this.sprvObjects;
	}

	public void setSprvObjects(SprvObjects sprvObjects) {
		this.sprvObjects = sprvObjects;
	}

*/
	public double getSpmdUid() {
		return this.spmdUid;
	}

	public void setSpmdUid(double spmdUid) {
		this.spmdUid = spmdUid;
	}
	
	public long getSpmdSpmtId() {
		return this.spmdSpmtId;
	}

	public void setSpmdSpmtId(long spmdSpmtId) {
		this.spmdSpmtId = spmdSpmtId;
	}
	
	public long getSpmdSpobId() {
		return this.spmdSpobId;
	}

	public void setSpmdSpobId(long spmdSpobId) {
		this.spmdSpobId = spmdSpobId;
	}
	
	public String getSpmdName() {
		return this.spmdName;
	}

	public void setSpmdName(String spmdName) {
		this.spmdName = spmdName;
	}

	public Date getSpmdDtCreate() {
		return this.spmdDtCreate;
	}

	public void setSpmdDtCreate(Date spmdDtCreate) {
		this.spmdDtCreate = spmdDtCreate;
	}

	public Date getSpmdDtClose() {
		return this.spmdDtClose;
	}

	public void setSpmdDtClose(Date spmdDtClose) {
		this.spmdDtClose = spmdDtClose;
	}

	public String getSpmdUser() {
		return this.spmdUser;
	}

	public void setSpmdUser(String spmdUser) {
		this.spmdUser = spmdUser;
	}

	public String getSpmdImei() {
		return this.spmdImei;
	}

	public void setSpmdImei(String spmdImei) {
		this.spmdImei = spmdImei;
	}

	public String getSpmdNumb() {
		return this.spmdNumb;
	}

	public void setSpmdNumb(String spmdNumb) {
		this.spmdNumb = spmdNumb;
	}

	public String getSpmdDesc() {
		return this.spmdDesc;
	}

	public void setSpmdDesc(String spmdDesc) {
		this.spmdDesc = spmdDesc;
	}

	public String getSpmdSpmtName() {
		return this.spmdSpmtName;
	}
	public void setSpmdSpmtName(String spmdSpmtName) {
		this.spmdSpmtName = spmdSpmtName;
	}

	public String getSpmdSpobName() {
		return this.spmdSpobName;
	}
	public void setSpmdSpobName(String spmdSpobName) {
		this.spmdSpobName = spmdSpobName;
	}
}
