package ru.novaris.novoscan.domain;

/*import java.util.HashSet;
import java.util.Set;*/

/**
 * SprvSensors generated by hbm2java
 */
public class SprvSensors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spsnId;

	private SprvSensorTypes sprvSensorTypes;

	private SprvModules sprvModules;

	private double spsnUin;

	private String spsnName;

	private String spsnDesc;

	public SprvSensors() {
	}

	public SprvSensors(long spsnId, SprvModules sprvModules, double spsnUin,
			String spsnName) {
		this.spsnId = spsnId;
		this.sprvModules = sprvModules;
		this.spsnUin = spsnUin;
		this.spsnName = spsnName;
	}
	public SprvSensors(double spsnUin) {
		this.spsnUin = spsnUin;
	}

/*	public SprvSensors(long spsnId, SprvSensorTypes sprvSensorTypes,
			SprvModules sprvModules, double spsnUin, String spsnName,
			String spsnDesc, Set dataSensors, Set sprvCalibrates) {
		this.spsnId = spsnId;
		this.sprvSensorTypes = sprvSensorTypes;
		this.sprvModules = sprvModules;
		this.spsnUin = spsnUin;
		this.spsnName = spsnName;
		this.spsnDesc = spsnDesc;
		this.dataSensors = dataSensors;
		this.sprvCalibrates = sprvCalibrates;
	}*/

	public long getSpsnId() {
		return this.spsnId;
	}

	public void setSpsnId(long spsnId) {
		this.spsnId = spsnId;
	}
	
	public SprvSensorTypes getSprvSensorTypes() {
		return this.sprvSensorTypes;
	}

	public void setSprvSensorTypes(SprvSensorTypes sprvSensorTypes) {
		this.sprvSensorTypes = sprvSensorTypes;
	}

	public SprvModules getSprvModules() {
		return this.sprvModules;
	}

	public void setSprvModules(SprvModules sprvModules) {
		this.sprvModules = sprvModules;
	}

	public double getSpsnUin() {
		return this.spsnUin;
	}

	public void setSpsnUin(double spsnUin) {
		this.spsnUin = spsnUin;
	}

	public String getSpsnName() {
		return this.spsnName;
	}

	public void setSpsnName(String spsnName) {
		this.spsnName = spsnName;
	}

	public String getSpsnDesc() {
		return this.spsnDesc;
	}

	public void setSpsnDesc(String spsnDesc) {
		this.spsnDesc = spsnDesc;
	}

/*	public Set getDataSensors() {
		return this.dataSensors;
	}

	public void setDataSensors(Set dataSensors) {
		this.dataSensors = dataSensors;
	}

	public Set getSprvCalibrates() {
		return this.sprvCalibrates;
	}

	public void setSprvCalibrates(Set sprvCalibrates) {
		this.sprvCalibrates = sprvCalibrates;
	}*/

}
