package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * SprvCalibrate generated by hbm2java
 */
public class SprvCalibrate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int spcbId;

	private SprvUnits sprvUnits;

	private SprvSensors sprvSensors;

	private String spcbData;

	private int spcbType;

	private Date spcbDtCreate;

	private Date spcbDtModify;

	private Date spcbDtClose;

	public SprvCalibrate() {
	}

	public SprvCalibrate(int spcbId, SprvUnits sprvUnits,
			SprvSensors sprvSensors, String spcbData, int spcbType,
			Date spcbDtCreate, Date spcbDtModify) {
		this.spcbId = spcbId;
		this.sprvUnits = sprvUnits;
		this.sprvSensors = sprvSensors;
		this.spcbData = spcbData;
		this.spcbType = spcbType;
		this.spcbDtCreate = spcbDtCreate;
		this.spcbDtModify = spcbDtModify;
	}

	public SprvCalibrate(int spcbId, SprvUnits sprvUnits,
			SprvSensors sprvSensors, String spcbData, int spcbType,
			Date spcbDtCreate, Date spcbDtModify, Date spcbDtClose) {
		this.spcbId = spcbId;
		this.sprvUnits = sprvUnits;
		this.sprvSensors = sprvSensors;
		this.spcbData = spcbData;
		this.spcbType = spcbType;
		this.spcbDtCreate = spcbDtCreate;
		this.spcbDtModify = spcbDtModify;
		this.spcbDtClose = spcbDtClose;
	}

	public int getSpcbId() {
		return this.spcbId;
	}

	public void setSpcbId(int spcbId) {
		this.spcbId = spcbId;
	}

	public SprvUnits getSprvUnits() {
		return this.sprvUnits;
	}

	public void setSprvUnits(SprvUnits sprvUnits) {
		this.sprvUnits = sprvUnits;
	}

	public SprvSensors getSprvSensors() {
		return this.sprvSensors;
	}

	public void setSprvSensors(SprvSensors sprvSensors) {
		this.sprvSensors = sprvSensors;
	}

	public String getSpcbData() {
		return this.spcbData;
	}

	public void setSpcbData(String spcbData) {
		this.spcbData = spcbData;
	}

	public int getSpcbType() {
		return this.spcbType;
	}

	public void setSpcbType(int spcbType) {
		this.spcbType = spcbType;
	}

	public Date getSpcbDtCreate() {
		return this.spcbDtCreate;
	}

	public void setSpcbDtCreate(Date spcbDtCreate) {
		this.spcbDtCreate = spcbDtCreate;
	}

	public Date getSpcbDtModify() {
		return this.spcbDtModify;
	}

	public void setSpcbDtModify(Date spcbDtModify) {
		this.spcbDtModify = spcbDtModify;
	}

	public Date getSpcbDtClose() {
		return this.spcbDtClose;
	}

	public void setSpcbDtClose(Date spcbDtClose) {
		this.spcbDtClose = spcbDtClose;
	}

}
