package ru.novaris.novoscan.domain;

//import java.util.HashSet;
//import java.util.Set;

/**
 * SprvObjectTypes generated by hbm2java
 */
public class SprvObjectTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spotId;

	private String spotName;

	private String spotDesc;

//	private Set sprvObjectses = new HashSet(0);

	public SprvObjectTypes() {
	}

	public SprvObjectTypes(long spotId, String spotName, String spotDesc) {
		this.spotId = spotId;
		this.spotName = spotName;
		this.spotDesc = spotDesc;
	}

/*	public SprvObjectTypes(long spotId, String spotName, String spotDesc,
			Set sprvObjectses) {
		this.spotId = spotId;
		this.spotName = spotName;
		this.spotDesc = spotDesc;
		this.sprvObjectses = sprvObjectses;
	}*/

	public long getSpotId() {
		return this.spotId;
	}

	public void setSpotId(long spotId) {
		this.spotId = spotId;
	}

	public String getSpotName() {
		return this.spotName;
	}

	public void setSpotName(String spotName) {
		this.spotName = spotName;
	}

	public String getSpotDesc() {
		return this.spotDesc;
	}

	public void setSpotDesc(String spotDesc) {
		this.spotDesc = spotDesc;
	}

/*	public Set getSprvObjectses() {
		return this.sprvObjectses;
	}

	public void setSprvObjectses(Set sprvObjectses) {
		this.sprvObjectses = sprvObjectses;
	}*/

}
