package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * SysDictonary generated by hbm2java
 */
public class SysDictonary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long sdicId;

	private String sdicName;

	private double sdicType;

	private String sdicCvalue;

	private Date sdicDtCreate;

	public SysDictonary() {
	}

	public SysDictonary(long sdicId, String sdicName, double sdicType,
			String sdicCvalue, Date sdicDtCreate) {
		this.sdicId = sdicId;
		this.sdicName = sdicName;
		this.sdicType = sdicType;
		this.sdicCvalue = sdicCvalue;
		this.sdicDtCreate = sdicDtCreate;
	}

	public long getSdicId() {
		return this.sdicId;
	}

	public void setSdicId(long sdicId) {
		this.sdicId = sdicId;
	}

	public String getSdicName() {
		return this.sdicName;
	}

	public void setSdicName(String sdicName) {
		this.sdicName = sdicName;
	}

	public double getSdicType() {
		return this.sdicType;
	}

	public void setSdicType(double sdicType) {
		this.sdicType = sdicType;
	}

	public String getSdicCvalue() {
		return this.sdicCvalue;
	}

	public void setSdicCvalue(String sdicCvalue) {
		this.sdicCvalue = sdicCvalue;
	}

	public Date getSdicDtCreate() {
		return this.sdicDtCreate;
	}

	public void setSdicDtCreate(Date sdicDtCreate) {
		this.sdicDtCreate = sdicDtCreate;
	}

}
