CREATE ROLE T01_OPER_DEV;
CREATE ROLE T01_OPER_WWW;
CREATE ROLE T02_ADM_DEV;
CREATE ROLE T02_ADM_WWW;
CREATE ROLE T03_SPRV_DEV;
CREATE ROLE T04_ADM_DATA_SENS;
CREATE ROLE T04_OPER_DATA_SENS;
CREATE ROLE TRACK_SERVER_ALL;