package ru.novaris.novoscan.domain;

// Generated 12.10.2011 18:15:28 by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * AccountLists generated by hbm2java
 */
public class Acl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long acclId;

	private long acclRefId1;

	private long acclRefType1;

	private long acclRefId2;

	private long acclRefType2;

	private long acclAcl;

	private Date acclDt;

	private String acclRefName1;

	private String acclRefName2;

	public Acl() {
	}

	public Acl(long acclId, long acclRefId1, long acclRefType1,
			long acclRefId2, long acclRefType2, long acclAcl, Date acclDt) {
		this.acclId = acclId;
		this.acclRefId1 = acclRefId1;
		this.acclRefType1 = acclRefType1;
		this.acclRefId2 = acclRefId2;
		this.acclRefType2 = acclRefType2;
		this.acclAcl = acclAcl;
		this.acclDt = acclDt;
	}

	public long getAcclId() {
		return this.acclId;
	}

	public void setAcclId(long acclId) {
		this.acclId = acclId;
	}

	public long getAcclRefId1() {
		return this.acclRefId1;
	}

	public void setAcclRefId1(long acclRefId1) {
		this.acclRefId1 = acclRefId1;
	}

	public long getAcclRefType1() {
		return this.acclRefType1;
	}

	public void setAcclRefType1(long acclRefType1) {
		this.acclRefType1 = acclRefType1;
	}

	public long getAcclRefId2() {
		return this.acclRefId2;
	}

	public void setAcclRefId2(long acclRefId2) {
		this.acclRefId2 = acclRefId2;
	}

	public long getAcclRefType2() {
		return this.acclRefType2;
	}

	public void setAcclRefType2(long acclRefType2) {
		this.acclRefType2 = acclRefType2;
	}

	public long getAcclAcl() {
		return this.acclAcl;
	}

	public void setAcclAcl(long acclAcl) {
		this.acclAcl = acclAcl;
	}

	public Date getAcclDt() {
		return this.acclDt;
	}

	public void setAcclDt(Date acclDt) {
		this.acclDt = acclDt;
	}

	public String getAcclRefName1() {
		// TODO Auto-generated method stub
		return this.acclRefName1;
	}
	public void setAcclRefName1(String acctRefName1) {
		// TODO Auto-generated method stub
		this.acclRefName1 = acctRefName1;
	}
	public String getAcclRefName2() {
		// TODO Auto-generated method stub
		return this.acclRefName2;
	}
	public void setAcclRefName2(String acctRefName2) {
		// TODO Auto-generated method stub
		this.acclRefName2 = acctRefName2;
	}

}
