package ru.novaris.novoscan.domain;

/**
 * AllClientInfo1 generated by hbm2java
 */
public class AllClientInfo1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AllClientInfo1Id id;

	public AllClientInfo1() {
	}

	public AllClientInfo1(AllClientInfo1Id id) {
		this.id = id;
	}

	public AllClientInfo1Id getId() {
		return this.id;
	}

	public void setId(AllClientInfo1Id id) {
		this.id = id;
	}

}
