package ru.novaris.novoscan.domain;

/**
 * AllClientInfo generated by hbm2java
 */
public class AllClientInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AllClientInfoId id;

	public AllClientInfo() {
	}

	public AllClientInfo(AllClientInfoId id) {
		this.id = id;
	}

	public AllClientInfoId getId() {
		return this.id;
	}

	public void setId(AllClientInfoId id) {
		this.id = id;
	}

}
