package ru.novaris.novoscan.domain;

import java.util.Date;
/*import java.util.HashSet;
import java.util.Set;*/

/**
 * GisErrors generated by hbm2java
 */
public class GisErrors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int gserId;

	private String gserDesc;

	private Date gserDt;

//	private Set gisObjectses = new HashSet(0);

	public GisErrors() {
	}

	public GisErrors(int gserId, Date gserDt) {
		this.gserId = gserId;
		this.gserDt = gserDt;
	}

/*	public GisErrors(int gserId, String gserDesc, Date gserDt, Set gisObjectses) {
		this.gserId = gserId;
		this.gserDesc = gserDesc;
		this.gserDt = gserDt;
		this.gisObjectses = gisObjectses;
	}*/

	public int getGserId() {
		return this.gserId;
	}

	public void setGserId(int gserId) {
		this.gserId = gserId;
	}

	public String getGserDesc() {
		return this.gserDesc;
	}

	public void setGserDesc(String gserDesc) {
		this.gserDesc = gserDesc;
	}

	public Date getGserDt() {
		return this.gserDt;
	}

	public void setGserDt(Date gserDt) {
		this.gserDt = gserDt;
	}

/*	public Set getGisObjectses() {
		return this.gisObjectses;
	}

	public void setGisObjectses(Set gisObjectses) {
		this.gisObjectses = gisObjectses;
	}*/

}
