package ru.novaris.novoscan.domain;

/**
 * GisObjectsAttr generated by hbm2java
 */
public class GisObjectsAttr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int gsatId;

	private GisAttrTypes gisAttrTypes;

	private GisObjects gisObjects;

	private Integer gsatAttr;

	private Double gsatAttr1;

	private Double gsatAttr2;

	public GisObjectsAttr() {
	}

	public GisObjectsAttr(int gsatId) {
		this.gsatId = gsatId;
	}

	public GisObjectsAttr(int gsatId, GisAttrTypes gisAttrTypes,
			GisObjects gisObjects, Integer gsatAttr, Double gsatAttr1,
			Double gsatAttr2) {
		this.gsatId = gsatId;
		this.gisAttrTypes = gisAttrTypes;
		this.gisObjects = gisObjects;
		this.gsatAttr = gsatAttr;
		this.gsatAttr1 = gsatAttr1;
		this.gsatAttr2 = gsatAttr2;
	}

	public int getGsatId() {
		return this.gsatId;
	}

	public void setGsatId(int gsatId) {
		this.gsatId = gsatId;
	}

	public GisAttrTypes getGisAttrTypes() {
		return this.gisAttrTypes;
	}

	public void setGisAttrTypes(GisAttrTypes gisAttrTypes) {
		this.gisAttrTypes = gisAttrTypes;
	}

	public GisObjects getGisObjects() {
		return this.gisObjects;
	}

	public void setGisObjects(GisObjects gisObjects) {
		this.gisObjects = gisObjects;
	}

	public Integer getGsatAttr() {
		return this.gsatAttr;
	}

	public void setGsatAttr(Integer gsatAttr) {
		this.gsatAttr = gsatAttr;
	}

	public Double getGsatAttr1() {
		return this.gsatAttr1;
	}

	public void setGsatAttr1(Double gsatAttr1) {
		this.gsatAttr1 = gsatAttr1;
	}

	public Double getGsatAttr2() {
		return this.gsatAttr2;
	}

	public void setGsatAttr2(Double gsatAttr2) {
		this.gsatAttr2 = gsatAttr2;
	}

}
