package ru.novaris.novoscan.domain;

import java.util.Date;
/*import java.util.HashSet;
import java.util.Set;*/

/**
 * GisPointTypes generated by hbm2java
 */
public class GisPointTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int gsptId;

	private String gsptName;

	private String gsptDesc;

	private Date gsptDt;

//	private Set gisDatas = new HashSet(0);

	public GisPointTypes() {
	}

	public GisPointTypes(int gsptId, String gsptName, Date gsptDt) {
		this.gsptId = gsptId;
		this.gsptName = gsptName;
		this.gsptDt = gsptDt;
	}

/*	public GisPointTypes(int gsptId, String gsptName, String gsptDesc,
			Date gsptDt, Set gisDatas) {
		this.gsptId = gsptId;
		this.gsptName = gsptName;
		this.gsptDesc = gsptDesc;
		this.gsptDt = gsptDt;
		this.gisDatas = gisDatas;
	}*/

	public int getGsptId() {
		return this.gsptId;
	}

	public void setGsptId(int gsptId) {
		this.gsptId = gsptId;
	}

	public String getGsptName() {
		return this.gsptName;
	}

	public void setGsptName(String gsptName) {
		this.gsptName = gsptName;
	}

	public String getGsptDesc() {
		return this.gsptDesc;
	}

	public void setGsptDesc(String gsptDesc) {
		this.gsptDesc = gsptDesc;
	}

	public Date getGsptDt() {
		return this.gsptDt;
	}

	public void setGsptDt(Date gsptDt) {
		this.gsptDt = gsptDt;
	}

/*	public Set getGisDatas() {
		return this.gisDatas;
	}

	public void setGisDatas(Set gisDatas) {
		this.gisDatas = gisDatas;
	}
*/
}
