package ru.novaris.novoscan.domain;

/**
 * MvClientsId generated by hbm2java
 */
public class MvClientsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long acctId;

	private Long spclId;

	private String spclName;

	private String spclTypeName;

	private String spclDesc;

	private Long spclSpdpId;

	public MvClientsId() {
	}

	public MvClientsId(Long acctId, Long spclId, String spclName,
			String spclTypeName, String spclDesc, Long spclSpdpId) {
		this.acctId = acctId;
		this.spclId = spclId;
		this.spclName = spclName;
		this.spclTypeName = spclTypeName;
		this.spclDesc = spclDesc;
		this.spclSpdpId = spclSpdpId;
	}

	public Long getAcctId() {
		return this.acctId;
	}

	public void setAcctId(Long acctId) {
		this.acctId = acctId;
	}

	public Long getSpclId() {
		return this.spclId;
	}

	public void setSpclId(Long spclId) {
		this.spclId = spclId;
	}

	public String getSpclName() {
		return this.spclName;
	}

	public void setSpclName(String spclName) {
		this.spclName = spclName;
	}

	public String getSpclTypeName() {
		return this.spclTypeName;
	}

	public void setSpclTypeName(String spclTypeName) {
		this.spclTypeName = spclTypeName;
	}

	public String getSpclDesc() {
		return this.spclDesc;
	}

	public void setSpclDesc(String spclDesc) {
		this.spclDesc = spclDesc;
	}

	public Long getSpclSpdpId() {
		return this.spclSpdpId;
	}

	public void setSpclSpdpId(Long spclSpdpId) {
		this.spclSpdpId = spclSpdpId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MvClientsId))
			return false;
		MvClientsId castOther = (MvClientsId) other;

		return ((this.getAcctId() == castOther.getAcctId()) || (this
				.getAcctId() != null && castOther.getAcctId() != null && this
				.getAcctId().equals(castOther.getAcctId())))
				&& ((this.getSpclId().equals(castOther.getSpclId())) || (this
						.getSpclId() != null && castOther.getSpclId() != null && this
						.getSpclId().equals(castOther.getSpclId())))
				&& ((this.getSpclName() == castOther.getSpclName()) || (this
						.getSpclName() != null
						&& castOther.getSpclName() != null && this
						.getSpclName().equals(castOther.getSpclName())))
				&& ((this.getSpclTypeName().equals(castOther.getSpclTypeName()) ) || (this
						.getSpclTypeName() != null
						&& castOther.getSpclTypeName() != null && this
						.getSpclTypeName().equals(castOther.getSpclTypeName())))
				&& ((this.getSpclDesc().equals(castOther.getSpclDesc())) || (this
						.getSpclDesc() != null
						&& castOther.getSpclDesc() != null && this
						.getSpclDesc().equals(castOther.getSpclDesc())))
				&& ((this.getSpclSpdpId().equals(castOther.getSpclSpdpId()) ) || (this
						.getSpclSpdpId() != null
						&& castOther.getSpclSpdpId() != null && this
						.getSpclSpdpId().equals(castOther.getSpclSpdpId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAcctId() == null ? 0 : this.getAcctId().hashCode());
		result = 37 * result
				+ (getSpclId() == null ? 0 : this.getSpclId().hashCode());
		result = 37 * result
				+ (getSpclName() == null ? 0 : this.getSpclName().hashCode());
		result = 37
				* result
				+ (getSpclTypeName() == null ? 0 : this.getSpclTypeName()
						.hashCode());
		result = 37 * result
				+ (getSpclDesc() == null ? 0 : this.getSpclDesc().hashCode());
		result = 37
				* result
				+ (getSpclSpdpId() == null ? 0 : this.getSpclSpdpId()
						.hashCode());
		return result;
	}

}
