package ru.novaris.novoscan.domain;

/**
 * MvClients generated by hbm2java
 */
public class MvClients implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MvClientsId id;

	public MvClients() {
	}

	public MvClients(MvClientsId id) {
		this.id = id;
	}

	public MvClientsId getId() {
		return this.id;
	}

	public void setId(MvClientsId id) {
		this.id = id;
	}

}
