package ru.novaris.novoscan.domain;

/**
 * MvDeparts generated by hbm2java
 */
public class MvDeparts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MvDepartsId id;

	public MvDeparts() {
	}

	public MvDeparts(MvDepartsId id) {
		this.id = id;
	}

	public MvDepartsId getId() {
		return this.id;
	}

	public void setId(MvDepartsId id) {
		this.id = id;
	}

}
