package ru.novaris.novoscan.domain;

/**
 * MvDepartsId generated by hbm2java
 */
public class MvDepartsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long spdpId;

	private String spdpName;

	private Long acctId;

	public MvDepartsId() {
	}

	public MvDepartsId(Long spdpId, String spdpName, Long acctId) {
		this.spdpId = spdpId;
		this.spdpName = spdpName;
		this.acctId = acctId;
	}

	public Long getSpdpId() {
		return this.spdpId;
	}

	public void setSpdpId(Long spdpId) {
		this.spdpId = spdpId;
	}

	public String getSpdpName() {
		return this.spdpName;
	}

	public void setSpdpName(String spdpName) {
		this.spdpName = spdpName;
	}

	public Long getAcctId() {
		return this.acctId;
	}

	public void setAcctId(Long acctId) {
		this.acctId = acctId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MvDepartsId))
			return false;
		MvDepartsId castOther = (MvDepartsId) other;

		return ((this.getSpdpId() == castOther.getSpdpId()) || (this
				.getSpdpId() != null && castOther.getSpdpId() != null && this
				.getSpdpId().equals(castOther.getSpdpId())))
				&& ((this.getSpdpName() == castOther.getSpdpName()) || (this
						.getSpdpName() != null
						&& castOther.getSpdpName() != null && this
						.getSpdpName().equals(castOther.getSpdpName())))
				&& ((this.getAcctId().equals(castOther.getAcctId())) || (this
						.getAcctId() != null && castOther.getAcctId() != null && this
						.getAcctId().equals(castOther.getAcctId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSpdpId() == null ? 0 : this.getSpdpId().hashCode());
		result = 37 * result
				+ (getSpdpName() == null ? 0 : this.getSpdpName().hashCode());
		result = 37 * result
				+ (getAcctId() == null ? 0 : this.getAcctId().hashCode());
		return result;
	}

}
