package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * QueueModuleExec generated by hbm2java
 */
public class QueueModuleExec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long qumxId;

	private SprvModules sprvModules;

	private String qumxCommand;

	private int qumxStatus;

	private Date qumxDate;

	private Integer qumxStatusExec;

	private String qumxResult;

	private Date qumxDateExec;

	private String qumxUser;

	public QueueModuleExec() {
	}

	public QueueModuleExec(long qumxId, String qumxCommand, int qumxStatus,
			Date qumxDate) {
		this.qumxId = qumxId;
		this.qumxCommand = qumxCommand;
		this.qumxStatus = qumxStatus;
		this.qumxDate = qumxDate;
	}

	public QueueModuleExec(long qumxId, SprvModules sprvModules,
			String qumxCommand, int qumxStatus, Date qumxDate,
			Integer qumxStatusExec, String qumxResult, Date qumxDateExec,
			String qumxUser) {
		this.qumxId = qumxId;
		this.sprvModules = sprvModules;
		this.qumxCommand = qumxCommand;
		this.qumxStatus = qumxStatus;
		this.qumxDate = qumxDate;
		this.qumxStatusExec = qumxStatusExec;
		this.qumxResult = qumxResult;
		this.qumxDateExec = qumxDateExec;
		this.qumxUser = qumxUser;
	}

	public long getQumxId() {
		return this.qumxId;
	}

	public void setQumxId(long qumxId) {
		this.qumxId = qumxId;
	}

	public SprvModules getSprvModules() {
		return this.sprvModules;
	}

	public void setSprvModules(SprvModules sprvModules) {
		this.sprvModules = sprvModules;
	}

	public String getQumxCommand() {
		return this.qumxCommand;
	}

	public void setQumxCommand(String qumxCommand) {
		this.qumxCommand = qumxCommand;
	}

	public int getQumxStatus() {
		return this.qumxStatus;
	}

	public void setQumxStatus(int qumxStatus) {
		this.qumxStatus = qumxStatus;
	}

	public Date getQumxDate() {
		return this.qumxDate;
	}

	public void setQumxDate(Date qumxDate) {
		this.qumxDate = qumxDate;
	}

	public Integer getQumxStatusExec() {
		return this.qumxStatusExec;
	}

	public void setQumxStatusExec(Integer qumxStatusExec) {
		this.qumxStatusExec = qumxStatusExec;
	}

	public String getQumxResult() {
		return this.qumxResult;
	}

	public void setQumxResult(String qumxResult) {
		this.qumxResult = qumxResult;
	}

	public Date getQumxDateExec() {
		return this.qumxDateExec;
	}

	public void setQumxDateExec(Date qumxDateExec) {
		this.qumxDateExec = qumxDateExec;
	}

	public String getQumxUser() {
		return this.qumxUser;
	}

	public void setQumxUser(String qumxUser) {
		this.qumxUser = qumxUser;
	}

}
