package ru.novaris.novoscan.domain;

import java.math.BigDecimal;
import java.sql.Date;



/**
 * SprvObjectTypes generated by hbm2java
 */
public class SprvReportParameters implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spprId;

	private long spprSprpId;

	private String spprName;

	private String spprDesc;
	
	private String spprType;
	
	private BigDecimal spprValuen;
	
	private String spprValuev;

	private Date spprValued;

	private String spprHashMap;
	

//	private Set sprvObjectses = new HashSet(0);

	public SprvReportParameters() {
	}

	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
	}
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,BigDecimal spprValuen
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValuen = spprValuen;
	}
	
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,int spprValuen
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValuen = BigDecimal.valueOf(spprValuen);
	}
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,long spprValuen
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValuen = BigDecimal.valueOf(spprValuen);
	}
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,double spprValuen
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValuen = BigDecimal.valueOf(spprValuen);
	}
	
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,String spprValuev
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValuev = spprValuev;
	}
	public SprvReportParameters(long spprId
			,long spprSprpId
			,String spprName
			,String spprDesc
			,String spprType
			,Date spprValued
			) {
		this.spprId = spprId;
		this.spprSprpId = spprSprpId;
		this.spprName = spprName;
		this.spprDesc = spprDesc;
		this.spprType = spprType;
		this.spprValued = spprValued;
	}
	
	public long getSpprId() {
		return spprId;
	}

	public void setSpprId(long spprId) {
		this.spprId = spprId;
	}

	public long getSpprSprpId() {
		return spprSprpId;
	}

	public void setSpprSprpId(long spprSprpId) {
		this.spprSprpId = spprSprpId;
	}

	public String getSpprName() {
		return spprName;
	}

	public void setSpprName(String spprName) {
		this.spprName = spprName;
	}

	public String getSpprDesc() {
		return spprDesc;
	}

	public void setSpprDesc(String spprDesc) {
		this.spprDesc = spprDesc;
	}

	public String getSpprType() {
		return spprType;
	}

	public void setSpprType(String spprType) {
		this.spprType = spprType;
	}

	public BigDecimal getSpprValuen() {
		return spprValuen;
	}

	public void setSpprValuen(BigDecimal spprValuen) {
		this.spprValuen = spprValuen;
	}

	public String getSpprValuev() {
		return spprValuev;
	}

	public void setSpprValuev(String spprValuev) {
		this.spprValuev = spprValuev;
	}

	public Date getSpprValued() {
		return spprValued;
	}

	public void setSpprValued(Date spprValued) {
		this.spprValued = spprValued;
	}

	public String getSpprHashMap() {
		return this.spprHashMap;
	}
	public void setSpprHashMap(String spprHashMap) {
		this.spprHashMap = spprHashMap;
	}
}
