package ru.novaris.novoscan.domain;

/**
 * SprvCisInfo generated by hbm2java
 */
public class SprvCisInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int spciId;

	private GisTypes gisTypes;

	private int spciCode;

	private String spciDesc;

	public SprvCisInfo() {
	}

	public SprvCisInfo(int spciId, GisTypes gisTypes, int spciCode) {
		this.spciId = spciId;
		this.gisTypes = gisTypes;
		this.spciCode = spciCode;
	}

	public SprvCisInfo(int spciId, GisTypes gisTypes, int spciCode,
			String spciDesc) {
		this.spciId = spciId;
		this.gisTypes = gisTypes;
		this.spciCode = spciCode;
		this.spciDesc = spciDesc;
	}

	public int getSpciId() {
		return this.spciId;
	}

	public void setSpciId(int spciId) {
		this.spciId = spciId;
	}

	public GisTypes getGisTypes() {
		return this.gisTypes;
	}

	public void setGisTypes(GisTypes gisTypes) {
		this.gisTypes = gisTypes;
	}

	public int getSpciCode() {
		return this.spciCode;
	}

	public void setSpciCode(int spciCode) {
		this.spciCode = spciCode;
	}

	public String getSpciDesc() {
		return this.spciDesc;
	}

	public void setSpciDesc(String spciDesc) {
		this.spciDesc = spciDesc;
	}

}
