package ru.novaris.novoscan.domain;

/*import java.util.HashSet;
import java.util.Set;*/

/**
 * SprvSensorTypes generated by hbm2java
 */
public class SprvSensorTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long spstId;

	private String spstName;

	private String spstDesc;

//	private Set sprvSensorses = new HashSet(0);

	public SprvSensorTypes() {
	}

	public SprvSensorTypes(long spstId, String spstName, String spstDesc) {
		this.spstId = spstId;
		this.spstName = spstName;
		this.spstDesc = spstDesc;
	}

/*	public SprvSensorTypes(long spstId, String spstName, String spstDesc,
			Set sprvSensorses) {
		this.spstId = spstId;
		this.spstName = spstName;
		this.spstDesc = spstDesc;
		this.sprvSensorses = sprvSensorses;
	}*/

	public long getSpstId() {
		return this.spstId;
	}

	public void setSpstId(long spstId) {
		this.spstId = spstId;
	}

	public String getSpstName() {
		return this.spstName;
	}

	public void setSpstName(String spstName) {
		this.spstName = spstName;
	}

	public String getSpstDesc() {
		return this.spstDesc;
	}

	public void setSpstDesc(String spstDesc) {
		this.spstDesc = spstDesc;
	}

/*	public Set getSprvSensorses() {
		return this.sprvSensorses;
	}

	public void setSprvSensorses(Set sprvSensorses) {
		this.sprvSensorses = sprvSensorses;
	}
*/
}
