package ru.novaris.novoscan.domain;

import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;

/**
 * SprvArea generated by hbm2java
 */
public class SprvArea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long sparId;

	private String sparName;

	private Date sparDt;

//	private Set sprvClientses = new HashSet(0);

	public SprvArea() {
	}

	public SprvArea(long sparId, String sparName, Date sparDt) {
		this.sparId = sparId;
		this.sparName = sparName;
		this.sparDt = sparDt;
	}

/*	public SprvArea(long sparId, String sparName, Date sparDt, Set sprvClientses) {
		this.sparId = sparId;
		this.sparName = sparName;
		this.sparDt = sparDt;
		this.sprvClientses = sprvClientses;
	}*/

	public long getSparId() {
		return this.sparId;
	}

	public void setSparId(long sparId) {
		this.sparId = sparId;
	}

	public String getSparName() {
		return this.sparName;
	}

	public void setSparName(String sparName) {
		this.sparName = sparName;
	}

	public Date getSparDt() {
		return this.sparDt;
	}

	public void setSparDt(Date sparDt) {
		this.sparDt = sparDt;
	}

/*	public Set getSprvClientses() {
		return this.sprvClientses;
	}

	public void setSprvClientses(Set sprvClientses) {
		this.sprvClientses = sprvClientses;
	}*/

}
