package ru.novaris.novoscan.domain;

import java.util.Date;

/**
 * SysVariables generated by hbm2java
 */
public class SysVariables implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long svarId;

	private String svarName;

	private Double svarNvalue;

	private String svarCvalue;

	private Date svarDvalue;

	private Date svarDtCreate;

	private Date svarDtModify;

	private String svarDesc;

	public SysVariables() {
	}

	public SysVariables(long svarId, String svarName, Date svarDtCreate,
			Date svarDtModify, String svarDesc) {
		this.svarId = svarId;
		this.svarName = svarName;
		this.svarDtCreate = svarDtCreate;
		this.svarDtModify = svarDtModify;
		this.svarDesc = svarDesc;
	}

	public SysVariables(long svarId, String svarName, Double svarNvalue,
			String svarCvalue, Date svarDvalue, Date svarDtCreate,
			Date svarDtModify, String svarDesc) {
		this.svarId = svarId;
		this.svarName = svarName;
		this.svarNvalue = svarNvalue;
		this.svarCvalue = svarCvalue;
		this.svarDvalue = svarDvalue;
		this.svarDtCreate = svarDtCreate;
		this.svarDtModify = svarDtModify;
		this.svarDesc = svarDesc;
	}

	public long getSvarId() {
		return this.svarId;
	}

	public void setSvarId(long svarId) {
		this.svarId = svarId;
	}

	public String getSvarName() {
		return this.svarName;
	}

	public void setSvarName(String svarName) {
		this.svarName = svarName;
	}

	public Double getSvarNvalue() {
		return this.svarNvalue;
	}

	public void setSvarNvalue(Double svarNvalue) {
		this.svarNvalue = svarNvalue;
	}

	public String getSvarCvalue() {
		return this.svarCvalue;
	}

	public void setSvarCvalue(String svarCvalue) {
		this.svarCvalue = svarCvalue;
	}

	public Date getSvarDvalue() {
		return this.svarDvalue;
	}

	public void setSvarDvalue(Date svarDvalue) {
		this.svarDvalue = svarDvalue;
	}

	public Date getSvarDtCreate() {
		return this.svarDtCreate;
	}

	public void setSvarDtCreate(Date svarDtCreate) {
		this.svarDtCreate = svarDtCreate;
	}

	public Date getSvarDtModify() {
		return this.svarDtModify;
	}

	public void setSvarDtModify(Date svarDtModify) {
		this.svarDtModify = svarDtModify;
	}

	public String getSvarDesc() {
		return this.svarDesc;
	}

	public void setSvarDesc(String svarDesc) {
		this.svarDesc = svarDesc;
	}

}
